In [27]:
import numpy as np
import scipy
from sklearn.datasets import fetch_20newsgroups
from sklearn import decomposition
from sklearn.decomposition import NMF
from scipy import linalg
import matplotlib.pyplot as plt

In [29]:
A = scipy.sparse.random(5, 10, density = 0.1)
A
# print(A.A)

A = np.random.rand(5, 5)
print(np.around(A, 2))

[[ 0.21  0.76  0.69  0.98  0.17]
 [ 0.67  0.84  0.19  0.94  0.03]
 [ 0.58  0.71  0.11  0.75  0.7 ]
 [ 0.44  0.86  0.54  0.79  0.32]
 [ 0.3   0.94  0.9   0.53  0.62]]


In [30]:
# Do svd:
U, s, VT = linalg.svd(A)

In [31]:
print(np.around(U, 2))
print(np.around(s, 2))
print(np.around(VT, 2))

[[-0.45  0.15 -0.56 -0.66  0.17]
 [-0.44 -0.63 -0.28  0.48  0.33]
 [-0.41 -0.33  0.74 -0.41  0.06]
 [-0.46  0.03 -0.09  0.16 -0.87]
 [-0.48  0.69  0.22  0.38  0.32]]
[ 3.06  0.78  0.62  0.26  0.  ]
[[-0.32 -0.6  -0.37 -0.58 -0.27]
 [-0.46  0.04  0.75 -0.39  0.27]
 [ 0.25  0.   -0.33 -0.32  0.85]
 [ 0.51  0.45  0.09 -0.63 -0.36]
 [ 0.61 -0.66  0.43  0.07  0.02]]


In [49]:
# Do NMF
model = NMF(n_components=5, init='random')
W = model.fit_transform(A)
H = model.components_

In [50]:
print(np.around(W, 2))
print(np.around(H, 2))

[[ 0.89  0.63  0.    0.    0.29]
 [ 1.07  0.08  0.    0.84  0.  ]
 [ 0.89  0.    0.4   0.3   0.  ]
 [ 0.73  0.39  0.08  0.45  0.34]
 [ 0.36  0.43  0.09  0.33  0.98]]
[[ 0.24  0.39  0.13  0.8   0.02]
 [ 0.    0.49  0.66  0.42  0.05]
 [ 0.55  0.57  0.    0.06  1.72]
 [ 0.48  0.46  0.    0.07  0.  ]
 [ 0.    0.39  0.58  0.03  0.44]]
